Добавляет адаптивную сетку всех страниц
htmlacademy-adaptive/2146421-cat-energy-27 pull request #5
Opened 2022-12-11 22:02 UTC by Velkatya

2022-12-12 16:50 UTC, pavel-nyukalo requested changes
Так же не забывай, что все картинки и цвета, которые упираются в края макета - должны тянуться на всю ширину страницы

Например вот эти и тд

![image](https://user-images.githubusercontent.com/52506235/207104789-9a090f07-f436-427a-b920-403c9bf5e3db.png)

2022-12-12 16:50 UTC, pavel-nyukalo commented on source/catalog.html
> +        <ul class="main-nav__list site-list site-list">
Дублирование класса

2022-12-12 16:50 UTC, pavel-nyukalo commented on source/catalog.html
> +          <ul class="catalog__list">
Этот div кажется лишним.

Плюс немного нарушилась логика:

на планшете мы этому `div` даем сетку грид `324px 324px`

![image](https://user-images.githubusercontent.com/52506235/207096758-ec573b04-fa48-4b4b-af28-36badfae85b9.png)

Но при этом у него только один дочерний тег. Соответственно, он займет первую колонку и получается, что `ul` занимает первую колонку и ширина его 324px

![image](https://user-images.githubusercontent.com/52506235/207097086-6ee6e20f-d64a-4022-b572-fb4f7118fc2b.png)

А потом еще и `ul` задается сетка гридовая. В общем, этот див нужно убрать, он тут лишний

2022-12-12 16:50 UTC, pavel-nyukalo commented on source/catalog.html
> +      <section class="extra-products">
Элемент блока нельзя выносить из блока, он должен быть внутри этого блока

2022-12-12 16:50 UTC, pavel-nyukalo commented on source/catalog.html
> +          </div>
Отступы надо поправить

2022-12-12 16:50 UTC, pavel-nyukalo commented on source/form.html
> +              <label class="add__control">
Лишний отступ появился

2022-12-12 16:50 UTC, pavel-nyukalo commented on source/form.html
> +          </div>
Тут тоже лишний отступ

2022-12-12 16:50 UTC, pavel-nyukalo commented on source/form.html
> +      </div>
![image](https://user-images.githubusercontent.com/52506235/207100412-51015e47-b241-4605-808e-9525b1c64c16.png)

2022-12-12 16:50 UTC, pavel-nyukalo commented on source/index.html
> +      <div class="main-container__hero-desktop-background"></div>
Пустые теги для декора лучше не создавать, лучше завязываться либо на псевдоэлементы, либо на уже имеющиеся секции

2022-12-12 16:50 UTC, pavel-nyukalo commented on source/less/form/add.less
> +    grid-template-columns: 305px 305px 305px 305px;
Тут можно сократить до `grid-template-columns: repeat(4, 305px);`

2022-12-12 16:50 UTC, pavel-nyukalo commented on source/less/index/alive-example.less
> +    }
Получился медиа вложенный в медиа

2022-12-12 18:34 UTC, Velkatya commented on source/less/index/alive-example.less
> +    }
а как это поправить?

2022-12-14 10:42 UTC, pavel-nyukalo requested changes
Еще парочку моментов про адаптивность:

1. Вот этот блок думаю стоит центрировать от мобилки к планшету

![image](https://user-images.githubusercontent.com/52506235/207573214-2bcd272f-ec6b-4604-8588-ceb9e3378828.png)

2. Форма, вот тут хорошо тянется, от края до края

![image](https://user-images.githubusercontent.com/52506235/207573332-2ab7f594-72c1-4ee4-bbb8-547bce530704.png)

А вот если уже открыть на большом разрешении, то справа получается большое пространство. Его быть не должно. Либо центрируем контент, либо вот как на планшете тянем. Но тут мне кажется лучше просто отцентрировать

![image](https://user-images.githubusercontent.com/52506235/207573533-eda86b27-c853-4d05-8ce7-1e5c12887fcc.png)


3. Насчет этой штуки

Тут у нас уже нарушение ТЗ. По [ТЗ](https://up.htmlacademy.ru/adaptive/27/project/cat-energy#cat-energy-4-11) сказано, что это должно быть две равные части. Левая белая, правая зеленая плюс кот должен упираться в правый край экрана. То есть вот граница между белой частью и зеленой должна ровно по центру сайта быть

![image](https://user-images.githubusercontent.com/52506235/207573647-b3e4ab5e-6ddd-420a-8123-06ed3150fdbe.png)

2022-12-14 10:42 UTC, pavel-nyukalo commented on source/index.html
> +  <script src="script.js"></script>
Скрипты лучше в подпапку `js/` (так же все в `source/`) складывать

\* проверь еще написание названия, нет ли там русских `c`, а то на сервере он не видит файл 

![image](https://user-images.githubusercontent.com/52506235/207571379-f268ee65-c35c-492d-b061-daf29d8f0223.png)

2022-12-14 10:42 UTC, pavel-nyukalo commented on source/less/general/main-nav.less
> +    .main-nav--closed .site-list__item {
`site-list__item` здесь не должно быть, поскольку у нас это файл для `main-nav`. Надо завязываться на элементы `main-nav`

2022-12-14 10:42 UTC, pavel-nyukalo commented on source/less/general/main-nav.less
> +  .main-nav--closed .site-list__item--active a {
Так же, плюс тут вложенность 3 получилась, а по критериям нельзя больше 2

2022-12-15 10:59 UTC, pavel-nyukalo requested changes
Контент центрируем - хорошо. Но опять же, по ТЗ у нас зеленый цвет и кот упирается в правый край экрана, то есть он должен растягиваться. Но при этом Функциональное питание и картинку можно оставить по центру

![image](https://user-images.githubusercontent.com/52506235/207839834-986e0594-fcb3-4667-8f3f-412b0e7f7d8b.png)

И с цветами такая же история. То есть мы можем центрировать контент, это хорошо. А вот серый фон надо тянуть

![image](https://user-images.githubusercontent.com/52506235/207840122-cfaabeba-a611-416a-9844-f64b1254015c.png)

То есть смотрим на макет - вот красный блок центрируем, а цвета/картинки тянем

![image](https://user-images.githubusercontent.com/52506235/207840421-8ca1ccf0-7de0-4d25-ab55-0d4ae3e3d239.png)


Вот пример

Экран у нас 3000px - контент центрируем, остальное тянем

![image](https://user-images.githubusercontent.com/52506235/207842167-50caa3d6-c468-4bf8-a253-a0d8fd551473.png)

Вот пример с шапкой

![image](https://user-images.githubusercontent.com/52506235/207842261-e8497212-64a8-4a65-acb0-76ad22eea6cb.png)

2022-12-15 10:59 UTC, pavel-nyukalo commented on source/less/general/main-nav.less
> +    .main-nav--closed .site-list__item {
Тут не поправлен комментарий

2022-12-15 10:59 UTC, pavel-nyukalo commented on source/less/general/main-nav.less
> +  .main-nav--closed .site-list__item--active a {
Тут тоже

2022-12-16 15:44 UTC, pavel-nyukalo requested changes

2022-12-16 15:44 UTC, pavel-nyukalo commented on source/catalog.html
> +          </div>
Здесь опять добавился лишний отступ

2022-12-16 15:44 UTC, pavel-nyukalo commented on source/form.html
> +  </section>
Предлагаю делать единообразно. На других страницах у нас `contact-information` находится в `main`. Тут предлагаю так же

2022-12-16 15:44 UTC, pavel-nyukalo commented on source/less/general/main-nav.less
> +    .main-nav--closed .site-list__item {
Стилей для `.site-list__item` в этом файле быть не должно. Этот файл у нас только для блока `main-nav` и его элементов/модификаторов

2022-12-16 15:44 UTC, pavel-nyukalo commented on source/less/general/main-nav.less
> +.main-nav--nojs .site-list__item--active a {
Аналогично про `.site-list__item`.

Плюс вложенность больше 2 запрещена

2022-12-17 10:32 UTC, pavel-nyukalo approved these changes

2022-12-17 10:32 UTC, merged